[versions]
# https://fabricmc.net/develop/
fabric-loom = "1.17.+"
fabric-loader = "0.19.3"

# https://stonecutter.kikugie.dev/
stonecutter = "0.9.+"
# https://stonecutter.kikugie.dev/wiki/fletching-table/setup
fletching-table = "0.1.0-alpha.22"

# https://modrinth.com/mod/fabric-language-kotlin
kotlin = "2.4.10"
fabric-kotlin = "1.13.13+kotlin.2.4.10"

# this doesn't actually matter, we're dependency substituting anyway.
knit-loader = "0.1.0"

[libraries]
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
fabric-kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric-kotlin" }

knit-loader-fabric = { module = "xyz.bluspring.knit-loader:knit-loader-fabric", version.ref = "knit-loader" }
knit-loader-common = { module = "xyz.bluspring.knit-loader:knit-loader-quilt", version.ref = "knit-loader" }
knit-loader-quilt = { module = "xyz.bluspring.knit-loader:knit-loader-quilt", version.ref = "knit-loader" }

[bundles]
knit-loader = [
    "knit-loader-common",
    "knit-loader-fabric",
    "knit-loader-quilt",
]

[plugins]
fabric-loom = { id = "net.fabricmc.fabric-loom", version.ref = "fabric-loom" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fletching-table = { id = "dev.kikugie.fletching-table", version.ref = "fletching-table" }
stonecutter = { id = "dev.kikugie.stonecutter" }
